[package]
name = "rstorrent-engine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "rstorrent-download-piece"
path = "src/main.rs"

[[bin]]
name = "rstorrent-storage-stage-profile"
path = "src/storage_stage_profile_main.rs"

[dependencies]
async-compression = { workspace = true }
base64 = { workspace = true }
futures-util = { workspace = true }
getrandom = { workspace = true }
quick-xml = { workspace = true }
reqwest = { workspace = true }
rstorrent-protocol = { path = "../rstorrent-protocol" }
rustix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "rt", "sync", "time"] }
tokio-util = { workspace = true, features = ["rt"] }
url = { workspace = true }

[dev-dependencies]
tokio-rustls = "0.26.4"
