[package]
name = "rstorrent-engine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "rstorrent-download-piece"
path = "src/main.rs"

[dependencies]
getrandom = { workspace = true }
rstorrent-protocol = { path = "../rstorrent-protocol" }
sha1 = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "rt", "sync", "time"] }
tokio-util = { workspace = true, features = ["rt"] }
