[package]
name = "rstorrent-crostini"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
font8x8 = { version = "0.3.1", default-features = false, features = ["unicode"] }
x11rb = { version = "0.13.2", default-features = false }

[dev-dependencies]
tempfile = "3.23.0"
