#!/usr/bin/env python3
"""Bounded private seed for installed desktop/extension lifetime rehearsals.

Uses independently generated bytes and the existing libtorrent test oracle.
Run only for controlled test clients; fixture files are temporary evidence.
"""
import argparse
import hashlib
import ipaddress
import json
import signal
import socket
import struct
import threading
import time
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlsplit

import libtorrent as lt


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--bind", default="127.0.0.1")
    parser.add_argument("--seconds", type=int, default=900)
    args = parser.parse_args()
    address = ipaddress.ip_address(args.bind)
    if address.version != 4 or not (address.is_loopback or address.is_private) or address.is_unspecified:
        parser.error("bind must be one concrete private/loopback IPv4 address")
    if not 1 <= args.seconds <= 1800 or not args.root.is_absolute():
        parser.error("use an absolute new root and a 1..1800 second lifetime")
    if not lt.version.startswith("2.0.11"):
        raise RuntimeError("this rehearsal pins libtorrent 2.0.11")
    args.root.mkdir(parents=True, exist_ok=False)
    seed_root = args.root / "seed"
    seed_root.mkdir()
    name = "checkpoint-transfer.bin"
    block = bytes((index * 17 + index // 13) & 255 for index in range(65536))
    payload = block * 512
    (seed_root / name).write_bytes(payload)
    session = lt.session({
        "listen_interfaces": f"{address}:0", "enable_dht": False,
        "enable_lsd": False, "enable_upnp": False, "enable_natpmp": False,
        "enable_incoming_utp": False, "enable_outgoing_utp": False,
        "enable_incoming_tcp": True, "enable_outgoing_tcp": True,
        "connections_limit": 4, "upload_rate_limit": 256 * 1024,
        "alert_queue_size": 128,
    })
    deadline = time.monotonic() + 10
    while not session.listen_port() and time.monotonic() < deadline:
        time.sleep(0.02)
    if not session.listen_port():
        raise RuntimeError("seed listener did not become ready")
    compact_peer = socket.inet_aton(str(address)) + struct.pack("!H", session.listen_port())

    class Tracker(BaseHTTPRequestHandler):
        def do_GET(self):
            if len(self.path) > 8192 or urlsplit(self.path).path != "/announce":
                self.send_error(400)
                return
            query = parse_qs(urlsplit(self.path).query, encoding="latin1")
            if query.get("info_hash", [""])[0].encode("latin1").hex() != info_hash:
                self.send_error(400)
                return
            body = bytes(lt.bencode({b"interval": 10, b"peers": compact_peer}))
            self.send_response(200)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def log_message(self, *_args):
            pass

    class BoundedTracker(HTTPServer):
        def get_request(self):
            connection, peer = super().get_request()
            connection.settimeout(2)
            return connection, peer

    tracker = BoundedTracker((str(address), 0), Tracker)
    tracker.timeout = 1
    files = lt.file_storage()
    files.add_file(name, len(payload))
    creator = lt.create_torrent(files, piece_size=len(block), flags=lt.create_torrent.v1_only)
    creator.set_priv(True)
    creator.add_tracker(f"http://{address}:{tracker.server_port}/announce")
    lt.set_piece_hashes(creator, str(seed_root))
    metainfo = bytes(lt.bencode(creator.generate()))
    torrent_path = args.root / "checkpoint-transfer.torrent"
    torrent_path.write_bytes(metainfo)
    info = lt.torrent_info(str(torrent_path))
    info_hash = str(info.info_hashes().v1)
    parameters = lt.add_torrent_params()
    parameters.ti = info
    parameters.save_path = str(seed_root)
    parameters.flags &= ~lt.torrent_flags.paused
    parameters.flags &= ~lt.torrent_flags.auto_managed
    parameters.flags |= lt.torrent_flags.seed_mode
    handle = session.add_torrent(parameters)
    stopping = threading.Event()
    for kind in (signal.SIGINT, signal.SIGTERM):
        signal.signal(kind, lambda *_: stopping.set())
    thread = threading.Thread(target=tracker.serve_forever, daemon=True)
    thread.start()
    report = {"name": name, "bytes": len(payload), "sha256": hashlib.sha256(payload).hexdigest(),
              "infoHash": info_hash, "torrent": str(torrent_path), "libtorrent": lt.version}
    (args.root / "ready.json").write_text(json.dumps(report) + "\n")
    print(json.dumps(report), flush=True)
    try:
        deadline = time.monotonic() + args.seconds
        while not stopping.wait(0.2) and time.monotonic() < deadline:
            session.pop_alerts()
            if handle.status().errc.value():
                raise RuntimeError("controlled seed reported a failure")
    finally:
        tracker.shutdown()
        tracker.server_close()
        thread.join(timeout=2)
        session.pause()
        session.remove_torrent(handle)


if __name__ == "__main__":
    main()
